config multicast-relay 'general'
	option enabled '0'
	option interfaces '192.168.1.0/24 192.168.3.0/24'
	# option ttl '1'
	# option ssdpUnicastAddr ''
	# option mdnsForceUnicast '0'
	# option noMDNS '0'
	# option noSSDP '0'
	# option noSonosDiscovery '0'
	# option allowNonEther '0'
	# option masquerade ''
	# option verbose '0'